[build]
  command = "npm run build"
  publish = "dist"

# Asset redirects - bundled assets first
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# Legacy asset paths for compatibility  
[[redirects]]
  from = "/documents/*"
  to = "/documents/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

# SPA routing - catch all client-side routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for bundled assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/documents/*"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"
