services:
  - type: web
    name: sanjay-portfolio-node
    env: node
    plan: free
    buildCommand: |
      echo "=== Installing root dependencies ==="
      npm install --production
      echo "=== Building frontend ==="
      cd frontend
      npm ci --legacy-peer-deps
      npm run build
      cd ..
      echo "=== Build complete ==="
      ls -la frontend/dist/
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
