services:
  - type: web
    name: sanjay-portfolio
    env: static
    buildCommand: cd frontend && npm ci --legacy-peer-deps && npm run build
    staticPublishPath: frontend/dist
    routes:
      # Static assets - serve directly with proper paths
      - type: rewrite
        source: /assets/*
        destination: /assets/$1
      - type: rewrite
        source: /documents/*
        destination: /documents/$1
      - type: rewrite
        source: /images/*
        destination: /images/$1
      # Handle specific file extensions
      - type: rewrite
        source: /*.pdf
        destination: /$1.pdf
      - type: rewrite
        source: /*.jpg
        destination: /$1.jpg
      - type: rewrite
        source: /*.png
        destination: /$1.png
      - type: rewrite
        source: /*.svg
        destination: /$1.svg
      # SPA fallback for client-side routing - MUST be last
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /assets/*
        name: Cache-Control
        value: "public, max-age=31536000, immutable"
      - path: /documents/*
        name: Content-Type
        value: application/pdf
      - path: /documents/*
        name: Cache-Control
        value: "public, max-age=31536000"
      - path: /images/*
        name: Cache-Control
        value: "public, max-age=31536000"
      - path: "*.pdf"
        name: Content-Type
        value: application/pdf
      - path: "*.jpg"
        name: Content-Type
        value: image/jpeg
      - path: "*.png"
        name: Content-Type
        value: image/png
