services:
  - type: web
    name: sanjay-portfolio
    env: static
    buildCommand: cd frontend && npm ci --legacy-peer-deps && npm run build
    staticPublishPath: frontend/dist
    routes:
      # Static assets - serve directly (highest priority)
      - type: rewrite
        source: /assets/*
        destination: /assets/:splat
      - type: rewrite
        source: /documents/*
        destination: /documents/:splat
      - type: rewrite
        source: /images/*
        destination: /images/:splat

      # Handle file extensions
      - type: rewrite
        source: /*.pdf
        destination: /:splat.pdf
      - type: rewrite
        source: /*.jpg
        destination: /:splat.jpg
      - type: rewrite
        source: /*.png
        destination: /:splat.png
      - type: rewrite
        source: /*.svg
        destination: /:splat.svg
      - type: rewrite
        source: /*.js
        destination: /:splat.js
      - type: rewrite
        source: /*.css
        destination: /:splat.css

      # Explicit SPA routes - handle specific client-side routes
      - type: rewrite
        source: /about
        destination: /index.html
      - type: rewrite
        source: /projects
        destination: /index.html
      - type: rewrite
        source: /blog
        destination: /index.html
      - type: rewrite
        source: /contact
        destination: /index.html

      # SPA fallback for any other routes
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /assets/*
        name: Cache-Control
        value: "public, max-age=31536000, immutable"
      - path: /documents/*
        name: Content-Type
        value: application/pdf
      - path: /documents/*
        name: Cache-Control
        value: "public, max-age=31536000"
      - path: /images/*
        name: Cache-Control
        value: "public, max-age=31536000"
      - path: "*.pdf"
        name: Content-Type
        value: application/pdf
      - path: "*.jpg"
        name: Content-Type
        value: image/jpeg
      - path: "*.png"
        name: Content-Type
        value: image/png
